# Generated by Django 2.0.9 on 2025-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_master',
            name='odate',
            field=models.DateField(max_length=100),
        ),
    ]
