# Generated by Django 2.0.9 on 2025-01-08 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20250108_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('pin', models.IntegerField()),
                ('address', models.CharField(max_length=10000)),
                ('locality', models.CharField(max_length=200)),
                ('other', models.CharField(max_length=10000)),
                ('ORDER_MASTER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.order_master')),
            ],
        ),
    ]
