# Generated by Django 2.0.9 on 2025-01-08 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='district',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(default='sfsf', max_length=200),
            preserve_default=False,
        ),
    ]
